"""create clips table

Revision ID: 8e94b0730971
Revises: 
Create Date: 2026-08-06 00:17:39.786779

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8e94b0730971'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clips',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_url', sa.String(length=2048), nullable=False),
    sa.Column('platform', sa.Enum('YOUTUBE', 'INSTAGRAM', 'TWITTER', 'TIKTOK', name='platform_enum'), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=2048), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='clip_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clips_original_url'), 'clips', ['original_url'], unique=True)
    op.create_index(op.f('ix_clips_platform'), 'clips', ['platform'], unique=False)
    op.create_index(op.f('ix_clips_status'), 'clips', ['status'], unique=False)
    op.create_index(op.f('ix_clips_title'), 'clips', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clips_title'), table_name='clips')
    op.drop_index(op.f('ix_clips_status'), table_name='clips')
    op.drop_index(op.f('ix_clips_platform'), table_name='clips')
    op.drop_index(op.f('ix_clips_original_url'), table_name='clips')
    op.drop_table('clips')
    # ### end Alembic commands ###
