"""add users and clip ownership

Revision ID: dc1fe517afdd
Revises: 8e94b0730971
Create Date: 2026-08-08 00:07:12.700810

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dc1fe517afdd'
down_revision: str | Sequence[str] | None = '8e94b0730971'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.add_column('clips', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_clips_original_url'), table_name='clips')
    op.create_index(op.f('ix_clips_owner_id'), 'clips', ['owner_id'], unique=False)
    op.create_unique_constraint('uq_owner_original_url', 'clips', ['owner_id', 'original_url'])
    op.create_foreign_key(None, 'clips', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_clips_owner_id_users', 'clips', type_='foreignkey')
    op.drop_constraint('uq_owner_original_url', 'clips', type_='unique')
    op.drop_index(op.f('ix_clips_owner_id'), table_name='clips')
    op.create_index(op.f('ix_clips_original_url'), 'clips', ['original_url'], unique=True)
    op.drop_column('clips', 'owner_id')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
